# Generated by Django 5.2.10 on 2026-01-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imageUrl',
            field=models.URLField(blank=True, help_text='External image URL', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, help_text='Whether the article is published'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings'),
        ),
    ]
